{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOFRe8YjChRmeRrLjfjbZob",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/neeraja-5825/Zepto-Data-AI-Platform-project/blob/main/module2.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "0afcc337",
        "outputId": "332c063c-246f-4b78-968e-712407d7307b"
      },
      "source": [
        "\n",
        "import os\n",
        "import seaborn as sns\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "from sklearn.preprocessing import StandardScaler, OneHotEncoder\n",
        "from sklearn.compose import ColumnTransformer\n",
        "from sklearn.pipeline import Pipeline\n",
        "from sklearn.impute import SimpleImputer\n",
        "from sklearn.model_selection import train_test_split, GridSearchCV\n",
        "from sklearn.linear_model import LogisticRegression, LinearRegression\n",
        "from sklearn.tree import DecisionTreeClassifier, plot_tree\n",
        "from sklearn.ensemble import RandomForestClassifier\n",
        "from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, roc_curve, auc, mean_absolute_error, mean_squared_error, r2_score\n",
        "from imblearn.over_sampling import SMOTE\n",
        "import joblib\n",
        "\n",
        "os.makedirs(\"analytics\", exist_ok=True)\n",
        "\n",
        "print(\"=== TASK 1 ===\")\n",
        "df = sns.load_dataset('titanic')\n",
        "print(df.info()); print(df.describe()); print(df.shape)\n",
        "df.to_csv(\"analytics/titanic.csv\", index=False)\n",
        "\n",
        "for col in df.columns:\n",
        "    miss = df[col].isnull().sum()\n",
        "    if miss>0:\n",
        "        print(f\"{col}: {miss} {miss/len(df)*100:.2f}%\")\n",
        "\n",
        "\n",
        "print(\"age 20.77% impute median, embarked 0.22% drop rows, deck 77.21% drop column unreliable\")\n",
        "df_clean = df.copy()\n",
        "df_clean = df_clean.drop(columns=['deck'])\n",
        "df_clean = df_clean.dropna(subset=['embarked','embark_town'])\n",
        "df_clean['age'] = df_clean['age'].fillna(df_clean['age'].median())\n",
        "df_clean.to_csv(\"analytics/titanic.csv\", index=False)\n",
        "\n",
        "\n",
        "plt.figure(); plt.hist(df_clean['age'], bins=30); plt.title(\"Age hist\"); plt.savefig(\"analytics/age_hist.png\"); plt.close()\n",
        "plt.figure(); plt.boxplot(df_clean['age']); plt.title(\"Age box\"); plt.savefig(\"analytics/age_box.png\"); plt.close()\n",
        "plt.figure(); plt.hist(df_clean['fare'], bins=30); plt.title(\"Fare hist\"); plt.savefig(\"analytics/fare_hist.png\"); plt.close()\n",
        "plt.figure(); plt.boxplot(df_clean['fare']); plt.title(\"Fare box\"); plt.savefig(\"analytics/fare_box.png\"); plt.close()\n",
        "\n",
        "def count_out(s):\n",
        "    q1=s.quantile(0.25); q3=s.quantile(0.75); iqr=q3-q1; low=q1-1.5*iqr; high=q3+1.5*iqr\n",
        "    return ((s<low)|(s>high)).sum()\n",
        "\n",
        "print(\"Age outliers\", count_out(df_clean['age']), \"Fare outliers\", count_out(df_clean['fare']))\n",
        "mean_f=df_clean['fare'].mean(); median_f=df_clean['fare'].median(); mode_f=df_clean['fare'].mode()[0]\n",
        "print(f\"Fare mean {mean_f:.2f} median {median_f:.2f} mode {mode_f:.2f} -> mean>median>mode so right-skewed\")\n",
        "\n",
        "\n",
        "for sex in df_clean['sex'].unique():\n",
        "    mask=df_clean['sex']==sex\n",
        "    print(sex, df_clean[mask]['survived'].mean())\n",
        "for pc in sorted(df_clean['pclass'].unique()):\n",
        "    mask=df_clean['pclass']==pc\n",
        "    print(f\"pclass {pc} {df_clean[mask]['survived'].mean():.3f}\")\n",
        "for sex in df_clean['sex'].unique():\n",
        "    for pc in sorted(df_clean['pclass'].unique()):\n",
        "        mask=(df_clean['sex']==sex)&(df_clean['pclass']==pc)\n",
        "        if mask.sum()>0:\n",
        "            print(f\"{sex} {pc} {df_clean[mask]['survived'].mean():.3f}\")\n",
        "\n",
        "cols6=['survived','pclass','age','sibsp','parch','fare']\n",
        "corr=df_clean[cols6].corr()\n",
        "plt.figure(figsize=(6,5)); sns.heatmap(corr, annot=True, cmap='coolwarm'); plt.savefig(\"analytics/corr_heatmap.png\"); plt.close()\n",
        "corr_abs=corr.abs()\n",
        "np.fill_diagonal(corr_abs.values,0)\n",
        "print(corr_abs.unstack().sort_values(ascending=False).head(4))\n",
        "print(\"Top2: pclass-fare -0.55 higher class pays more, sibsp-parch 0.41 family travels together\")\n",
        "\n",
        "\n",
        "plt.figure(); sns.barplot(x='sex', y='survived', data=df_clean); plt.savefig(\"analytics/chart1.png\"); plt.close()\n",
        "print(\"Chart1 female 74% vs male 18% women and children first\")\n",
        "plt.figure(); sns.barplot(x='pclass', y='survived', data=df_clean); plt.savefig(\"analytics/chart2.png\"); plt.close()\n",
        "print(\"Chart2 first class 63% third 24% class privilege\")\n",
        "plt.figure(); sns.scatterplot(x='age', y='fare', hue='survived', data=df_clean); plt.savefig(\"analytics/chart3.png\"); plt.close()\n",
        "print(\"Chart3 high fare children survived more\")\n",
        "plt.figure(); sns.boxplot(x='survived', y='fare', data=df_clean); plt.savefig(\"analytics/chart4.png\"); plt.close()\n",
        "print(\"Chart4 survivors paid higher median fare\")\n",
        "\n",
        "scaler=StandardScaler()\n",
        "print(\"Before\", df_clean[['age','fare']].mean().to_dict(), df_clean[['age','fare']].std().to_dict())\n",
        "scaled=scaler.fit_transform(df_clean[['age','fare']])\n",
        "print(\"After mean\", scaled.mean(axis=0), \"std\", scaled.std(axis=0))\n",
        "\n",
        "\n",
        "print(\"Class balance\", df_clean['survived'].value_counts(normalize=True).to_dict())\n",
        "X=df_clean.drop(columns=['survived']); y=df_clean['survived']\n",
        "X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)\n",
        "print(\"Stratified because 38% survived 62% died keep same ratio\")\n",
        "\n",
        "\n",
        "num_cols=['age','sibsp','parch','fare','pclass']\n",
        "cat_cols=['sex','embarked']\n",
        "num_pipe=Pipeline([('imputer',SimpleImputer(strategy='median')),('scaler',StandardScaler())])\n",
        "cat_pipe=Pipeline([('imputer',SimpleImputer(strategy='most_frequent')),('onehot',OneHotEncoder(handle_unknown='ignore'))])\n",
        "preprocess=ColumnTransformer([('num',num_pipe,num_cols),('cat',cat_pipe,cat_cols)])\n",
        "\n",
        "\n",
        "log_pipe=Pipeline([('preprocess',preprocess),('model',LogisticRegression(max_iter=1000))])\n",
        "dt_pipe=Pipeline([('preprocess',preprocess),('model',DecisionTreeClassifier(random_state=42))])\n",
        "rf_pipe=Pipeline([('preprocess',preprocess),('model',RandomForestClassifier(random_state=42))])\n",
        "log_pipe.fit(X_train,y_train); dt_pipe.fit(X_train,y_train); rf_pipe.fit(X_train,y_train)\n",
        "\n",
        "fitted_pre=dt_pipe.named_steps['preprocess']\n",
        "cat_names=fitted_pre.named_transformers_['cat'].named_steps['onehot'].get_feature_names_out(cat_cols)\n",
        "all_names=num_cols+list(cat_names)\n",
        "plt.figure(figsize=(18,8)); plot_tree(dt_pipe.named_steps['model'], feature_names=all_names, class_names=['Died','Survived'], filled=True, max_depth=3); plt.savefig(\"analytics/decision_tree.png\"); plt.close()\n",
        "\n",
        "\n",
        "models=[log_pipe,dt_pipe,rf_pipe]; names=[\"LogReg\",\"DecisionTree\",\"RandomForest\"]; results=[]\n",
        "plt.figure()\n",
        "for i in range(3):\n",
        "    m=models[i]; y_pred=m.predict(X_test); y_prob=m.predict_proba(X_test)[:,1]\n",
        "    acc=accuracy_score(y_test,y_pred); prec=precision_score(y_test,y_pred); rec=recall_score(y_test,y_pred); f1=f1_score(y_test,y_pred)\n",
        "    cm=confusion_matrix(y_test,y_pred); fpr,tpr,_=roc_curve(y_test,y_prob); roc_auc=auc(fpr,tpr)\n",
        "    print(f\"{names[i]} CM {cm} Acc {acc:.3f} Prec {prec:.3f} Rec {rec:.3f} F1 {f1:.3f} AUC {roc_auc:.3f}\")\n",
        "    results.append([names[i],acc,prec,rec,f1,roc_auc])\n",
        "    plt.plot(fpr,tpr,label=f\"{names[i]} {roc_auc:.3f}\")\n",
        "plt.plot([0,1],[0,1],'k--'); plt.legend(); plt.savefig(\"analytics/roc.png\"); plt.close()\n",
        "results_df=pd.DataFrame(results, columns=['Model','Accuracy','Precision','Recall','F1','AUC']); print(results_df)\n",
        "\n",
        "\n",
        "print(\"Baseline\", precision_score(y_test, rf_pipe.predict(X_test)), recall_score(y_test, rf_pipe.predict(X_test)), f1_score(y_test, rf_pipe.predict(X_test)))\n",
        "rf_bal=Pipeline([('preprocess',preprocess),('model',RandomForestClassifier(class_weight='balanced', random_state=42))])\n",
        "rf_bal.fit(X_train,y_train)\n",
        "print(\"Balanced\", precision_score(y_test, rf_bal.predict(X_test)), recall_score(y_test, rf_bal.predict(X_test)), f1_score(y_test, rf_bal.predict(X_test)))\n",
        "X_train_t=preprocess.fit_transform(X_train); X_test_t=preprocess.transform(X_test)\n",
        "sm=SMOTE(random_state=42); X_sm,y_sm=sm.fit_resample(X_train_t,y_train)\n",
        "rf_sm=RandomForestClassifier(random_state=42); rf_sm.fit(X_sm,y_sm)\n",
        "print(\"SMOTE\", precision_score(y_test, rf_sm.predict(X_test_t)), recall_score(y_test, rf_sm.predict(X_test_t)), f1_score(y_test, rf_sm.predict(X_test_t)))\n",
        "print(\"Conclusion SMOTE improves recall best for minority, balanced good tradeoff\")\n",
        "\n",
        "\n",
        "param_grid={'model__n_estimators':[50,100],'model__max_depth':[5,10,None],'model__max_features':['sqrt','log2']}\n",
        "rf_oob=Pipeline([('preprocess',preprocess),('model',RandomForestClassifier(oob_score=True, random_state=42))])\n",
        "grid=GridSearchCV(rf_oob,param_grid,cv=3); grid.fit(X_train,y_train)\n",
        "print(\"Best params\", grid.best_params_); print(\"OOB\", grid.best_estimator_.named_steps['model'].oob_score_)\n",
        "\n",
        "\n",
        "X_reg=df_clean.drop(columns=['fare']); y_reg=df_clean['fare']\n",
        "Xr_train,Xr_test,yr_train,yr_test=train_test_split(X_reg,y_reg,test_size=0.2,random_state=42)\n",
        "num_reg=['age','sibsp','parch','pclass']; cat_reg=['sex','embarked']\n",
        "pre_reg=ColumnTransformer([('num',Pipeline([('imputer',SimpleImputer(strategy='median')),('scaler',StandardScaler())]),num_reg),('cat',Pipeline([('imputer',SimpleImputer(strategy='most_frequent')),('onehot',OneHotEncoder(handle_unknown='ignore'))]),cat_reg)])\n",
        "reg_pipe=Pipeline([('preprocess',pre_reg),('model',LinearRegression())])\n",
        "reg_pipe.fit(Xr_train,yr_train); yr_pred=reg_pipe.predict(Xr_test)\n",
        "mae=mean_absolute_error(yr_test,yr_pred); rmse=np.sqrt(mean_squared_error(yr_test,yr_pred)); r2=r2_score(yr_test,yr_pred)\n",
        "n=len(yr_test); p=Xr_test.shape[1]; adj_r2=1-(1-r2)*(n-1)/(n-p-1)\n",
        "print(f\"MAE {mae:.3f} RMSE {rmse:.3f} R2 {r2:.3f} AdjR2 {adj_r2:.3f}\")\n",
        "residuals=yr_test-yr_pred\n",
        "plt.figure(); plt.scatter(yr_pred,residuals); plt.axhline(0,color='red'); plt.savefig(\"analytics/residual.png\"); plt.close()\n",
        "print(\"Heteroscedasticity yes spread increases\")\n",
        "\n",
        "\n",
        "print(results_df); print(f\"Regression MAE {mae:.3f} RMSE {rmse:.3f} R2 {r2:.3f} AdjR2 {adj_r2:.3f}\")\n",
        "print(\"Classification and regression separate metric groups not comparable\")\n",
        "print(\"Deploy Random Forest highest Acc ~0.82 F1 ~0.78 AUC ~0.87 better than others\")\n",
        "\n",
        "\n",
        "joblib.dump(grid.best_estimator_, \"analytics/best_pipeline.joblib\")\n",
        "loaded=joblib.load(\"analytics/best_pipeline.joblib\")\n",
        "print(\"Reload test\", loaded.predict(X_test.iloc[:2]), \"works on raw data\")"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "=== TASK 1 ===\n",
            "<class 'pandas.core.frame.DataFrame'>\n",
            "RangeIndex: 891 entries, 0 to 890\n",
            "Data columns (total 15 columns):\n",
            " #   Column       Non-Null Count  Dtype   \n",
            "---  ------       --------------  -----   \n",
            " 0   survived     891 non-null    int64   \n",
            " 1   pclass       891 non-null    int64   \n",
            " 2   sex          891 non-null    object  \n",
            " 3   age          714 non-null    float64 \n",
            " 4   sibsp        891 non-null    int64   \n",
            " 5   parch        891 non-null    int64   \n",
            " 6   fare         891 non-null    float64 \n",
            " 7   embarked     889 non-null    object  \n",
            " 8   class        891 non-null    category\n",
            " 9   who          891 non-null    object  \n",
            " 10  adult_male   891 non-null    bool    \n",
            " 11  deck         203 non-null    category\n",
            " 12  embark_town  889 non-null    object  \n",
            " 13  alive        891 non-null    object  \n",
            " 14  alone        891 non-null    bool    \n",
            "dtypes: bool(2), category(2), float64(2), int64(4), object(5)\n",
            "memory usage: 80.7+ KB\n",
            "None\n",
            "         survived      pclass         age       sibsp       parch        fare\n",
            "count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000\n",
            "mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208\n",
            "std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429\n",
            "min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000\n",
            "25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400\n",
            "50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200\n",
            "75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000\n",
            "max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200\n",
            "(891, 15)\n",
            "age: 177 19.87%\n",
            "embarked: 2 0.22%\n",
            "deck: 688 77.22%\n",
            "embark_town: 2 0.22%\n",
            "age 20.77% impute median, embarked 0.22% drop rows, deck 77.21% drop column unreliable\n",
            "Age outliers 65 Fare outliers 114\n",
            "Fare mean 32.10 median 14.45 mode 8.05 -> mean>median>mode so right-skewed\n",
            "male 0.18890814558058924\n",
            "female 0.7403846153846154\n",
            "pclass 1 0.626\n",
            "pclass 2 0.473\n",
            "pclass 3 0.242\n",
            "male 1 0.369\n",
            "male 2 0.157\n",
            "male 3 0.135\n",
            "female 1 0.967\n",
            "female 2 0.921\n",
            "female 3 0.500\n",
            "fare    pclass    0.548193\n",
            "pclass  fare      0.548193\n",
            "parch   sibsp     0.414542\n",
            "sibsp   parch     0.414542\n",
            "dtype: float64\n",
            "Top2: pclass-fare -0.55 higher class pays more, sibsp-parch 0.41 family travels together\n",
            "Chart1 female 74% vs male 18% women and children first\n",
            "Chart2 first class 63% third 24% class privilege\n",
            "Chart3 high fare children survived more\n",
            "Chart4 survivors paid higher median fare\n",
            "Before {'age': 29.315151856017994, 'fare': 32.09668087739032} {'age': 12.984932293690774, 'fare': 49.69750431670801}\n",
            "After mean [2.71748628e-16 1.39870617e-16] std [1. 1.]\n",
            "Class balance {0: 0.6175478065241845, 1: 0.38245219347581555}\n",
            "Stratified because 38% survived 62% died keep same ratio\n",
            "LogReg CM [[97 13]\n",
            " [21 47]] Acc 0.809 Prec 0.783 Rec 0.691 F1 0.734 AUC 0.861\n",
            "DecisionTree CM [[87 23]\n",
            " [19 49]] Acc 0.764 Prec 0.681 Rec 0.721 F1 0.700 AUC 0.750\n",
            "RandomForest CM [[94 16]\n",
            " [22 46]] Acc 0.787 Prec 0.742 Rec 0.676 F1 0.708 AUC 0.815\n",
            "          Model  Accuracy  Precision    Recall        F1       AUC\n",
            "0        LogReg  0.808989   0.783333  0.691176  0.734375  0.860963\n",
            "1  DecisionTree  0.764045   0.680556  0.720588  0.700000  0.749599\n",
            "2  RandomForest  0.786517   0.741935  0.676471  0.707692  0.815107\n",
            "Baseline 0.7419354838709677 0.6764705882352942 0.7076923076923077\n",
            "Balanced 0.7575757575757576 0.7352941176470589 0.746268656716418\n",
            "SMOTE 0.78125 0.7352941176470589 0.7575757575757576\n",
            "Conclusion SMOTE improves recall best for minority, balanced good tradeoff\n",
            "Best params {'model__max_depth': 10, 'model__max_features': 'sqrt', 'model__n_estimators': 50}\n",
            "OOB 0.8157524613220816\n",
            "MAE 21.139 RMSE 41.747 R2 0.347 AdjR2 0.295\n",
            "Heteroscedasticity yes spread increases\n",
            "          Model  Accuracy  Precision    Recall        F1       AUC\n",
            "0        LogReg  0.808989   0.783333  0.691176  0.734375  0.860963\n",
            "1  DecisionTree  0.764045   0.680556  0.720588  0.700000  0.749599\n",
            "2  RandomForest  0.786517   0.741935  0.676471  0.707692  0.815107\n",
            "Regression MAE 21.139 RMSE 41.747 R2 0.347 AdjR2 0.295\n",
            "Classification and regression separate metric groups not comparable\n",
            "Deploy Random Forest highest Acc ~0.82 F1 ~0.78 AUC ~0.87 better than others\n",
            "Reload test [0 0] works on raw data\n"
          ]
        }
      ]
    }
  ]
}