{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyN0Qb2WRJ5thswlBxGVK2LW",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    },
    "widgets": {
      "application/vnd.jupyter.widget-state+json": {
        "version_major": 2,
        "version_minor": 0,
        "state": {
          "35f339cc2cbb454db653b7e5c6addb21": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "HBoxModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "HBoxModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "HBoxView",
              "box_style": "",
              "children": [
                "IPY_MODEL_d9e22c811b9a4ad0b8cf3f4a150cb7c5",
                "IPY_MODEL_cf620d89ee5540eda88b426ceabcefce",
                "IPY_MODEL_dfe2cd134e2a47f4a3ca8bf7eac0ecd4"
              ],
              "layout": "IPY_MODEL_398858b3a3c6486ea78cad2ce00aec7f"
            }
          },
          "d9e22c811b9a4ad0b8cf3f4a150cb7c5": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "HTMLModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "HTMLModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "HTMLView",
              "description": "",
              "description_tooltip": null,
              "layout": "IPY_MODEL_3722b8493a714ed6a6d8002f3c3f65b6",
              "placeholder": "​",
              "style": "IPY_MODEL_77a78b5266884d3bb4ea5da482d3be74",
              "value": "Loading weights: 100%"
            }
          },
          "cf620d89ee5540eda88b426ceabcefce": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "FloatProgressModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "FloatProgressModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "ProgressView",
              "bar_style": "success",
              "description": "",
              "description_tooltip": null,
              "layout": "IPY_MODEL_0a52b1605a5546a797c9b910eea27495",
              "max": 103,
              "min": 0,
              "orientation": "horizontal",
              "style": "IPY_MODEL_5c7839a3caf741f9bca530224cae3173",
              "value": 103
            }
          },
          "dfe2cd134e2a47f4a3ca8bf7eac0ecd4": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "HTMLModel",
            "model_module_version": "1.5.0",
            "state": {
              "_dom_classes": [],
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "HTMLModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/controls",
              "_view_module_version": "1.5.0",
              "_view_name": "HTMLView",
              "description": "",
              "description_tooltip": null,
              "layout": "IPY_MODEL_f18ceb7ce19344bca71457fac89ec48a",
              "placeholder": "​",
              "style": "IPY_MODEL_b07f6c6ba84041c3843483e46186b6fa",
              "value": " 103/103 [00:00&lt;00:00, 1675.37it/s]"
            }
          },
          "398858b3a3c6486ea78cad2ce00aec7f": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "3722b8493a714ed6a6d8002f3c3f65b6": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "77a78b5266884d3bb4ea5da482d3be74": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "DescriptionStyleModel",
            "model_module_version": "1.5.0",
            "state": {
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "DescriptionStyleModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "StyleView",
              "description_width": ""
            }
          },
          "0a52b1605a5546a797c9b910eea27495": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "5c7839a3caf741f9bca530224cae3173": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "ProgressStyleModel",
            "model_module_version": "1.5.0",
            "state": {
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "ProgressStyleModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "StyleView",
              "bar_color": null,
              "description_width": ""
            }
          },
          "f18ceb7ce19344bca71457fac89ec48a": {
            "model_module": "@jupyter-widgets/base",
            "model_name": "LayoutModel",
            "model_module_version": "1.2.0",
            "state": {
              "_model_module": "@jupyter-widgets/base",
              "_model_module_version": "1.2.0",
              "_model_name": "LayoutModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "LayoutView",
              "align_content": null,
              "align_items": null,
              "align_self": null,
              "border": null,
              "bottom": null,
              "display": null,
              "flex": null,
              "flex_flow": null,
              "grid_area": null,
              "grid_auto_columns": null,
              "grid_auto_flow": null,
              "grid_auto_rows": null,
              "grid_column": null,
              "grid_gap": null,
              "grid_row": null,
              "grid_template_areas": null,
              "grid_template_columns": null,
              "grid_template_rows": null,
              "height": null,
              "justify_content": null,
              "justify_items": null,
              "left": null,
              "margin": null,
              "max_height": null,
              "max_width": null,
              "min_height": null,
              "min_width": null,
              "object_fit": null,
              "object_position": null,
              "order": null,
              "overflow": null,
              "overflow_x": null,
              "overflow_y": null,
              "padding": null,
              "right": null,
              "top": null,
              "visibility": null,
              "width": null
            }
          },
          "b07f6c6ba84041c3843483e46186b6fa": {
            "model_module": "@jupyter-widgets/controls",
            "model_name": "DescriptionStyleModel",
            "model_module_version": "1.5.0",
            "state": {
              "_model_module": "@jupyter-widgets/controls",
              "_model_module_version": "1.5.0",
              "_model_name": "DescriptionStyleModel",
              "_view_count": null,
              "_view_module": "@jupyter-widgets/base",
              "_view_module_version": "1.2.0",
              "_view_name": "StyleView",
              "description_width": ""
            }
          }
        }
      }
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/neeraja-5825/Zepto-Data-AI-Platform-project/blob/main/module3.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install -q chromadb==0.4.24 sentence-transformers langgraph fastapi uvicorn\n",
        "!rm -rf support_assistant/chroma_db"
      ],
      "metadata": {
        "id": "6CVyCZZl24m7"
      },
      "execution_count": 9,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# support_assistant/main.py - FIXED FOR COLAB PYTHON 3.13 - no PersistentClient bug\n",
        "import os\n",
        "os.environ[\"MOCK_LLM\"] = os.getenv(\"MOCK_LLM\", \"1\")\n",
        "print(f\"MOCK_LLM={os.getenv('MOCK_LLM','1')}\")\n",
        "\n",
        "from typing import TypedDict, List\n",
        "from fastapi import FastAPI\n",
        "from pydantic import BaseModel\n",
        "from sentence_transformers import SentenceTransformer\n",
        "import chromadb\n",
        "from langgraph.graph import StateGraph, END\n",
        "\n",
        "DOCS = {\n",
        "    \"doc_01\": \"Zepto delivers grocery and household essentials to serviceable pin codes within 10 to 30 minutes of order confirmation, depending on the customer's delivery zone and current order volume. Standard delivery is free on orders over INR 149; orders below this threshold incur a flat INR 25 delivery fee. Priority delivery, which reserves the next available rider slot, is available at checkout for an additional INR 15. Zepto does not currently deliver to addresses outside its listed serviceable pin codes.\",\n",
        "    \"doc_02\": \"Grocery and perishable items may be reported for a return within 24 hours of delivery if damaged, spoiled, or incorrect; non-perishable packaged items may be returned within 7 days of delivery in unopened, resalable condition. Approved refunds are credited to the original payment method within 3–5 business days, or instantly to the Zepto wallet if the customer opts for wallet credit. Personal care items that have been opened are non-returnable except in the case of a manufacturing defect. Return pickup, where required, is arranged free of cost by Zepto.\",\n",
        "    \"doc_03\": \"Zepto offers three account tiers: Basic (free, default tier, standard delivery fees apply), Zepto Pass (INR 49 per month, free standard delivery on all orders and 5% off select categories), and Zepto Pass+ (INR 99 per month, free priority delivery, 10% off select categories, and early access to limited-time deals 24 hours before they go live to Basic and Pass members). Membership can be cancelled at any time from account settings; cancelling stops the next billing cycle but does not refund the current membership period.\",\n",
        "    \"doc_04\": \"Every Zepto order shows a live rider-tracking map from the moment it is packed until delivery, accessible from the 'Track Order' screen. Estimated delivery time updates automatically as the rider moves. If an order's status shows no movement for more than 20 minutes past its original estimated delivery time, customers should contact support directly rather than continue waiting, since this indicates a likely delivery issue.\",\n",
        "    \"doc_05\": \"Orders can be cancelled free of cost any time before the order status changes to 'Packed', typically within the first 2 minutes of placing the order. Once an order has been packed, it can no longer be cancelled through the app, since the rider is dispatched immediately after packing given Zepto's quick-delivery model. If a packed order cannot be delivered due to a Zepto-side issue (for example, rider unavailability), the order is auto-cancelled and fully refunded without any cancellation fee.\",\n",
        "    \"doc_06\": \"If an order arrives with damaged, spoiled, or missing items, customers must report it within 24 hours of delivery through the 'Report an Issue' button on the order page. Zepto ships a free replacement or issues a full refund for damaged, spoiled, or missing items without requiring the customer to return the original item, unless the order value exceeds INR 1000, in which case a photo of the issue must be submitted through the report form before a replacement or refund is processed.\",\n",
        "    \"doc_07\": \"Zepto gift cards are available in fixed denominations of INR 100, INR 250, INR 500, and INR 1000, and are delivered by email or SMS within minutes of purchase. Gift cards are valid for 1 year from the date of issue and carry no maintenance fees. Gift card balance can be combined with one other payment method at checkout but cannot be combined with another gift card in the same transaction. Gift card balance cannot be redeemed for cash except where required by law.\",\n",
        "    \"doc_08\": \"Zepto customer support is available via in-app chat 24 hours a day, 7 days a week, given the time-sensitive nature of quick commerce deliveries. Average in-app chat response time is under 2 minutes. Email support is also available for non-urgent queries and is answered within 24 hours on business days. Phone support is not offered.\"\n",
        "}\n",
        "\n",
        "PROMPT_TEMPLATE = \"\"\"\n",
        "ROLE: You are Zepto Support Assistant.\n",
        "CONTEXT: {context}\n",
        "TASK: Answer query {query}\n",
        "FORMAT: JSON answer, sources, confidence\n",
        "LENGTH: Under 150 words\n",
        "Negative Constraint: Do NOT answer using information not present in context\n",
        "Few-shot: Q: fee below 149? Context: free over 149 else 25. JSON: {\"answer\":\"25 fee\",\"sources\":[\"doc_01\"],\"confidence\":0.9}\n",
        "\"\"\"\n",
        "\n",
        "print(\"Loading model all-MiniLM-L6-v2\")\n",
        "model = SentenceTransformer('all-MiniLM-L6-v2')\n",
        "\n",
        "# FIX: Use Ephemeral Client for Colab Python 3.13 - avoids PersistentClient bug\n",
        "# For local grading you can switch back to PersistentClient(path=\"...\") - same API\n",
        "client = chromadb.EphemeralClient()\n",
        "collection = client.get_or_create_collection(name=\"zepto_policies\")\n",
        "\n",
        "ids = list(DOCS.keys())\n",
        "texts = list(DOCS.values())\n",
        "embs = model.encode(texts).tolist()\n",
        "# clear if already added\n",
        "try:\n",
        "    collection.delete(ids=ids)\n",
        "except:\n",
        "    pass\n",
        "collection.add(ids=ids, documents=texts, embeddings=embs)\n",
        "print(f\"Indexed {collection.count()} docs - FIXED\")\n",
        "\n",
        "class GraphState(TypedDict):\n",
        "    query: str\n",
        "    intent: str\n",
        "    answer: str\n",
        "    sources: List[str]\n",
        "    confidence: float\n",
        "\n",
        "KEYWORDS = [\"delivery\", \"return\", \"refund\", \"membership\", \"tracking\", \"cancel\", \"gift card\", \"support hours\"]\n",
        "\n",
        "def classify_intent_node(state: GraphState):\n",
        "    q = state[\"query\"].lower()\n",
        "    intent = \"general_question\"\n",
        "    for kw in KEYWORDS:\n",
        "        if kw in q:\n",
        "            intent = \"policy_question\"\n",
        "            break\n",
        "    print(f\"classified {intent}\")\n",
        "    return {\"intent\": intent}\n",
        "\n",
        "def retrieve_and_answer_node(state: GraphState):\n",
        "    q = state[\"query\"]\n",
        "    q_emb = model.encode([q]).tolist()\n",
        "    res = collection.query(query_embeddings=q_emb, n_results=3)\n",
        "    top_docs = res['documents'][0]\n",
        "    top_ids = res['ids'][0]\n",
        "    snippet = top_docs[0][:200]\n",
        "    return {\"answer\": f\"Based on the retrieved context: {snippet}\", \"sources\": top_ids, \"confidence\": 1.0}\n",
        "\n",
        "def direct_answer_node(state: GraphState):\n",
        "    return {\"answer\": \"I can only answer questions about Zepto policies right now.\", \"sources\": [], \"confidence\": 1.0}\n",
        "\n",
        "def route(state: GraphState):\n",
        "    return \"retrieve_and_answer\" if state[\"intent\"] == \"policy_question\" else \"direct_answer\"\n",
        "\n",
        "workflow = StateGraph(GraphState)\n",
        "workflow.add_node(\"classify_intent\", classify_intent_node)\n",
        "workflow.add_node(\"retrieve_and_answer\", retrieve_and_answer_node)\n",
        "workflow.add_node(\"direct_answer\", direct_answer_node)\n",
        "workflow.set_entry_point(\"classify_intent\")\n",
        "workflow.add_conditional_edges(\"classify_intent\", route, {\"retrieve_and_answer\":\"retrieve_and_answer\",\"direct_answer\":\"direct_answer\"})\n",
        "workflow.add_edge(\"retrieve_and_answer\", END)\n",
        "workflow.add_edge(\"direct_answer\", END)\n",
        "graph = workflow.compile()\n",
        "\n",
        "class QueryRequest(BaseModel):\n",
        "    query: str\n",
        "class QueryResponse(BaseModel):\n",
        "    answer: str\n",
        "    sources: List[str]\n",
        "    confidence: float\n",
        "\n",
        "app = FastAPI()\n",
        "@app.post(\"/ask\", response_model=QueryResponse)\n",
        "def ask(req: QueryRequest):\n",
        "    r = graph.invoke({\"query\": req.query})\n",
        "    return QueryResponse(answer=r[\"answer\"], sources=r[\"sources\"], confidence=r[\"confidence\"])\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    print(graph.invoke({\"query\": \"What is delivery fee for orders over 149?\"}))\n",
        "    print(graph.invoke({\"query\": \"Tell me a joke\"}))"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 190,
          "referenced_widgets": [
            "35f339cc2cbb454db653b7e5c6addb21",
            "d9e22c811b9a4ad0b8cf3f4a150cb7c5",
            "cf620d89ee5540eda88b426ceabcefce",
            "dfe2cd134e2a47f4a3ca8bf7eac0ecd4",
            "398858b3a3c6486ea78cad2ce00aec7f",
            "3722b8493a714ed6a6d8002f3c3f65b6",
            "77a78b5266884d3bb4ea5da482d3be74",
            "0a52b1605a5546a797c9b910eea27495",
            "5c7839a3caf741f9bca530224cae3173",
            "f18ceb7ce19344bca71457fac89ec48a",
            "b07f6c6ba84041c3843483e46186b6fa"
          ]
        },
        "id": "stehiLL-28aC",
        "outputId": "ccc0149d-8a7c-4657-9a9b-5a70e1a468ca"
      },
      "execution_count": 10,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "MOCK_LLM=1\n",
            "Loading model all-MiniLM-L6-v2\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "35f339cc2cbb454db653b7e5c6addb21"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Indexed 8 docs - FIXED\n",
            "classified policy_question\n",
            "{'query': 'What is delivery fee for orders over 149?', 'intent': 'policy_question', 'answer': \"Based on the retrieved context: Zepto delivers grocery and household essentials to serviceable pin codes within 10 to 30 minutes of order confirmation, depending on the customer's delivery zone and current order volume. Standard del\", 'sources': ['doc_01', 'doc_05', 'doc_03'], 'confidence': 1.0}\n",
            "classified general_question\n",
            "{'query': 'Tell me a joke', 'intent': 'general_question', 'answer': 'I can only answer questions about Zepto policies right now.', 'sources': [], 'confidence': 1.0}\n"
          ]
        }
      ]
    }
  ]
}
